package alert

import (
	"time"
)

// Sismo represents the structured representation of a seismic event.
type Sismo struct {
	ID        string    `json:"id"`
	Source    string    `json:"source"` // "EMSC" | "Funvisis" | "Simulation"
	Magnitude float64   `json:"magnitude"`
	Depth     float64   `json:"depth"`
	Latitude  float64   `json:"latitude"`
	Longitude float64   `json:"longitude"`
	Location  string    `json:"location"`
	Time      time.Time `json:"time"`
	Distance  float64   `json:"distance"` // Distance to La Guaira in km
	GridCell  string    `json:"grid_cell"`
}

// PWaveTravelTime returns the estimated travel time of the P-wave to La Guaira.
func (s Sismo) PWaveTravelTime() time.Duration {
	if s.Distance <= 0 {
		return 0
	}
	return time.Duration(s.Distance / 6.0 * float64(time.Second))
}

// SWaveTravelTime returns the estimated travel time of the S-wave to La Guaira.
func (s Sismo) SWaveTravelTime() time.Duration {
	if s.Distance <= 0 {
		return 0
	}
	return time.Duration(s.Distance / 3.5 * float64(time.Second))
}

// PWaveArrivalTime returns the estimated arrival time of the P-wave at La Guaira.
func (s Sismo) PWaveArrivalTime() time.Time {
	return s.Time.Add(s.PWaveTravelTime())
}

// SWaveArrivalTime returns the estimated arrival time of the S-wave at La Guaira.
func (s Sismo) SWaveArrivalTime() time.Time {
	return s.Time.Add(s.SWaveTravelTime())
}

// AlertLevel represents the danger classification of a seismic alert.
type AlertLevel string

const (
	LevelInfo        AlertLevel = "INFO"
	LevelPreAlert    AlertLevel = "PRE_ALERT"
	LevelCritical    AlertLevel = "CRITICAL"
	LevelSwarm       AlertLevel = "SWARM"
	LevelInstability AlertLevel = "INSTABILITY"
)

// Alert wraps a seismic event with its evaluated threat level.
type Alert struct {
	Sismo        Sismo      `json:"sismo"`
	Level        AlertLevel `json:"level"`
	EarlyWarning bool       `json:"early_warning,omitempty"` // when true, notifier uses [EARLY WARNING] format
	Body         string     `json:"body,omitempty"`          // overrides default body when EarlyWarning is true
}

// ReportType identifies whether the LLM synthesis is an alert/confirmation or a calming/readjustment narrative.
type ReportType string

const (
	ReportConfirmacion ReportType = "CONFIRMACION"
	ReportCalmaReajuste ReportType = "CALMA_REAJUSTE"
)

// Citation represents a web source reference verified by Google Search Grounding.
type Citation struct {
	Title string `json:"title"`
	URL   string `json:"url"`
}

// SynthesisRequest contains the deterministic seismic state passed to Gemma 4.
type SynthesisRequest struct {
	TriggerType             string            `json:"trigger_type"` // e.g. "INESTABILIDAD_CORTICAL", "ENJAMBRE_PRECURSOR"
	FaultName               string            `json:"fault_name"`
	CellID                  string            `json:"cell_id"`
	BValue                  float64           `json:"b_value"`
	WeightedEnergy          float64           `json:"weighted_energy"`
	DynamicRate             float64           `json:"dynamic_rate"`
	Mainshock               Sismo             `json:"mainshock"`
	RecentEvents            []Sismo           `json:"recent_events"`
	Phase                   SwarmPhase        `json:"phase"`
	RecentHistoricalContext string            `json:"recent_historical_context"`
	AllProjections          []FaultProjection `json:"all_projections,omitempty"` // Vista completa del proyector
	AllPhases               []CellPhase       `json:"all_phases,omitempty"`      // Fases de todas las celdas
	LiveSismos              []Sismo           `json:"live_sismos,omitempty"`     // Sismos recientes del monitor
	PreviousReports         []SynthesisResponse `json:"previous_analyses_history,omitempty"` // Historial de los últimos reportes de la sesión
	UserLocation            string            `json:"user_location,omitempty"`            // Ubicación del usuario para evaluación de distancia/riesgo local
}

// SynthesisResponse contains the narrative report generated by Gemma 4.
type SynthesisResponse struct {
	ReportType  ReportType `json:"report_type"`
	Summary     string     `json:"summary"` // 1-2 line executive summary for notification titles
	Body        string     `json:"body"`    // Full conversational narrative report
	Citations   []Citation `json:"citations"`
	ModelUsed   string     `json:"model_used"`
	GeneratedAt time.Time  `json:"generated_at"`
}

